### ISSUE TITLE
Play again if statements all run

### ISSUE THREAD

**Issue by Ethan-Stark** [Broclly/Rogue.py#2]
In the `check()` function, it says ` if playAgain == "y" or "Y":`. That will run no matter the input because the non empty string "Y" is truthy, so effectively the if statement is `if true or playAgain == "y":`. 

Then since another if statement is used after with the same truthy issue, `if playAgain == "n" or "N":`, both run no matter what, and the game will always close.

Using the `upper()` or `lower()` function on the input means only one of those conditions needs to be checked (either just the uppercase letter or lowercase letter). There should also be an else statement to handle invalid inputs.

**Comment by Broclly** [comment]
This issue has been fixed with the new version, as I have changed the confirmation system to work with digits (1 and 0).
